"""new_food_column

Revision ID: 5a70bf454424
Revises: b70e10308638
Create Date: 2026-04-05 11:44:48.770500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a70bf454424'
down_revision: Union[str, Sequence[str], None] = 'b70e10308638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('webscraped_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'webscraped_image')
    # ### end Alembic commands ###
